name: Run Parallel Appium Tests

on:
  workflow_dispatch: # This allows you to run the workflow manually.
  repository_dispatch:
    types: [ run-parallel-tests ] # Allows external events to trigger this workflow

jobs:
  run-tests:
    runs-on: self-hosted # This specifies that the job should run on your self-hosted runner.

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5' # Specify the Python version you need
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    
    
    - name: Run parallel tests
      run: |
        python parallel_test.py
    

    - name: Run parallel tests
      run: python parallel_test.py
