name: Run github save file

on:
  workflow_dispatch:
    inputs:
      config_data:
        description: 'JSON Config Data'  # Describe your input here
        required: false
        default: ''  # Default value if none provided
  repository_dispatch:
    types: [run-github-tests]

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
    
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Create JSON File from CONFIG_DATA
      env:
        CONFIG_DATA: ${{ toJSON(github.event.client_payload.config_data) }}
      run: |
        echo "DEBUG: CONFIG_DATA content:"
        echo "$CONFIG_DATA"
        echo "$CONFIG_DATA" > config_data.json

    - name: Display JSON Config Data
      run: |
        touch config_data.json  # This is just to ensure the file exists for testing
        echo "Current directory: $(pwd)"
        echo "Listing files in current directory:"
        ls -l
        echo "Displaying JSON Config Data:"
        cat config_data.json || echo "File not found or empty"

    - name: Github commit and push
      uses: Smart-Transportation/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
            
